//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_2_4_Session.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapiska
    {
        public int Id { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> PaspisanieId { get; set; }
        public Nullable<bool> IsPredvar { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        public virtual Raspisanie Raspisanie { get; set; }
    }
}
